import { z } from 'astro/zod';
import { date, mediaKey, text } from './shared';

const researchImage = z.object({ image: mediaKey, alt: text, caption: text.optional() });

// Named sections mirror the existing visual components; all values are editorial.
export const pageSections = {
  whyCedhu: z.object({
    eyebrow: text,
    titleStart: text,
    titleEmphasis: text,
    introduction: text,
    image: mediaKey,
    photoCaption: text,
    experiences: z.array(z.object({
      title: text,
      description: text,
    })).min(5).max(6),
    linkLabel: text,
    linkHref: text,
  }).optional(),
  educationInterface: z.object({
    methodologyEyebrow: text,
    admissionsLabel: text,
    relatedEyebrow: text,
    pedagogyLabel: text,
  }).optional(),
  activities: z.object({
    eyebrow: text,
    title: text,
    registrationEyebrow: text,
    registrationTitle: text,
    registrationDescription: text,
    groups: z.array(z.object({
      title: text,
      items: z.array(text),
    })),
    forms: z.array(z.object({
      label: text,
      id: text,
    })),
  }).optional(),
  admissionsCta: z.object({
    linkHref: text,
    eyebrow: text,
    titleStart: text,
    titleEnd: text,
    description: text,
    linkLabel: text,
  }).optional(),
  admissionsProcess: z.object({
    documentsLinkHref: text,
    eyebrow: text,
    titleStart: text,
    titleEnd: text,
    introduction: text,
    noticeTitle: text,
    noticeDescription: text,
    whatsappLabel: text,
    phoneLabel: text,
    processEyebrow: text,
    processTitle: text,
    processDescription: text,
    documentsEyebrow: text,
    documentsTitle: text,
    documentsDescription: text,
    documentsNotice: text,
    documentsLinkLabel: text,
    steps: z.array(z.object({
      title: text,
      text: text,
      href: text.optional(),
      label: text.optional(),
    })),
  }).optional(),
  contactDetails: z.object({
    hoursLinkHref: text,
    emailEyebrow: text,
    emailTitle: text,
    whatsappLabel: text,
    phoneEyebrow: text,
    visitEyebrow: text,
    neighborhood: text,
    countrySuffix: text,
    mapsLabel: text,
    hoursEyebrow: text,
    hoursTitle: text,
    generalHoursLabel: text,
    weekdays: text,
    morningHours: text,
    afternoonHours: text,
    appointmentLabel: text,
    appointmentNotice: text,
    appointmentInstructions: text,
    hoursNotice: text,
    hoursLinkLabel: text,
    mapEyebrow: text,
    mapTitle: text,
    mapLinkLabel: text,
  }).optional(),
  documentsList: z.object({
    linkHref: text,
    eyebrow: text,
    title: text,
    description: text,
    linkLabel: text,
    items: z.array(z.object({
      id: text,
      title: text,
      category: text,
      description: text,
      file: text,
      source: text,
    })),
  }).optional(),
  educationalLevels: z.object({
    linkHref: text,
    eyebrow: text,
    title: text,
    linkLabel: text,
  }).optional(),
  educationOverview: z.object({
    pedagogyLinkHref: text,
    researchLinkHref: text,
    eyebrow: text,
    title: text,
    introduction: text,
    methodologyDescription: text,
    pedagogyLinkLabel: text,
    explorationEyebrow: text,
    explorationTitle: text,
    researchLinkLabel: text,
    image: mediaKey,
  }).optional(),
  faq: z.object({
    linkHref: text,
    eyebrow: text,
    titleStart: text,
    titleEnd: text,
    introduction: text,
    linkLabel: text,
    items: z.array(z.object({
      question: text,
      answer: text,
    })),
  }).optional(),
  hero: z.object({
    context: text,
    admissionsLabel: text,
    educationLabel: text,
    collageLabel: text,
    photoCaption: text,
    photoCaptionEmphasis: text,
    campusImage: mediaKey,
    campusCaption: text,
    playImage: mediaKey,
    playCaption: text,
    insetImage: mediaKey,
    insetLabel: text,
    footerDescription: text,
    discoverLabel: text,
    levelsLabel: text,
  }).optional(),
  historyTimeline: z.object({
    items: z.array(z.object({
      year: text,
      title: text,
      text: text,
    })),
  }).optional(),
  humanFormation: z.object({
    linkHref: text,
    image: mediaKey,
    photoCaption: text,
    eyebrow: text,
    titleStart: text,
    titleEnd: text,
    titleEmphasis: text,
    introduction: text,
    supportDescription: text,
    linkLabel: text,
  }).optional(),
  identityIntro: z.object({
    linkHref: text,
    eyebrow: text,
    titleStart: text,
    titleEnd: text,
    titleEmphasis: text,
    introduction: text,
    familyDescription: text,
    linkLabel: text,
    humanPillar: text,
    knowledgePillar: text,
    communityPillar: text,
  }).optional(),
  institutionIdentity: z.object({
    documentsLinkHref: text,
    principlesEyebrow: text,
    principlesTitle: text,
    valuesEyebrow: text,
    valuesTitle: text,
    mottoEyebrow: text,
    mottoStart: text,
    mottoEnd: text,
    mottoDescription: text,
    communicationTitle: text,
    communicationDescription: text,
    integrityDescription: text,
    symbolsEyebrow: text,
    image: mediaKey,
    flagTitle: text,
    flagDescription: text,
    emblemTitle: text,
    emblemDescription: text,
    uniformDescription: text,
    documentsLinkLabel: text,
    principles: z.array(z.object({
      title: text,
      text: text,
    })),
    values: z.array(z.object({
      title: text,
      text: text,
    })),
  }).optional(),
  institutionOverview: z.object({
    historyLinkHref: text,
    principlesLinkHref: text,
    pedagogyLinkHref: text,
    spacesLinkHref: text,
    teamLinkHref: text,
    documentsLinkHref: text,
    eyebrow: text,
    title: text,
    introduction: text,
    educationalApproach: text,
    familyDescription: text,
    historyLinkLabel: text,
    horizonEyebrow: text,
    missionTitle: text,
    visionTitle: text,
    image: mediaKey,
    identityEyebrow: text,
    identityTitleStart: text,
    identityTitleEnd: text,
    principlesLinkLabel: text,
    pedagogyLinkLabel: text,
    spacesLinkLabel: text,
    teamLinkLabel: text,
    documentsLinkLabel: text,
    mission: text,
    vision: text,
  }).optional(),
  institutionTeam: z.object({
    contactHref: text,
    hoursHref: text,
    eyebrow: text,
    title: text,
    introduction: text,
    contactDescription: text,
    contactLabel: text,
    hoursLabel: text,
  }).optional(),
  newsSection: z.object({
    linkHref: text,
    eyebrow: text,
    title: text,
    linkLabel: text,
  }).optional(),
  pedagogy: z.object({
    contactHref: text,
    quote: text,
    quoteAttribution: text,
    title: text,
    introduction: text,
    communicationDescription: text,
    valuesEyebrow: text,
    valuesTitle: text,
    image: mediaKey,
    supportEyebrow: text,
    supportTitle: text,
    supportDescription: text,
    familyDescription: text,
    contactLabel: text,
    ideas: z.array(z.object({
      title: text,
      text: text,
    })),
  }).optional(),
  quickAccess: z.object({
    eyebrow: text,
    titleStart: text,
    titleEnd: text,
    links: z.array(z.object({
      label: text,
      detail: text,
      href: text,
      external: z.boolean(),
    })),
  }).optional(),
  researchProjects: z.object({
    projects: z.array(z.object({
      title: text,
      slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
      summary: text,
      date: date.optional(),
      area: text.optional(),
      description: z.array(text).optional(),
      coverImage: researchImage.optional(),
      gallery: z.array(researchImage).optional(),
      authors: z.array(text).optional(),
      details: z.array(z.object({ label: text, value: text })).optional(),
      pdfs: z.array(z.object({
        title: text,
        href: z.string().regex(/^\/documentos\/investigacion\/(?:[a-z0-9-]+\/)*[a-z0-9-]+\.pdf$/),
      })).optional(),
      tags: z.array(text).optional(),
      featured: z.boolean().default(false),
      draft: z.boolean().default(false),
    })),
    educationLinkHref: text,
    eyebrow: text,
    title: text,
    introduction: text,
    publicationsDescription: text,
    projectsEyebrow: text,
    projectsTitle: text,
    emptyTitle: text,
    emptyDescription: text,
    educationLinkLabel: text,
  }).optional(),
  schoolSpaces: z.object({
    tourHref: text,
    visitHref: text,
    eyebrow: text,
    image: mediaKey,
    tourEyebrow: text,
    tourTitle: text,
    tourDescription: text,
    tourLabel: text,
    visitLabel: text,
    spaces: z.array(z.object({
      image: mediaKey,
      title: text,
      text: text,
    })),
  }).optional(),
  services: z.object({
    hoursHref: text,
    suppliesHref: text,
    activitiesHref: text,
    documentsHref: text,
    treasuryHref: text,
    booksHref: text,
    alumniHref: text,
    q10Name: text,
    q10Title: text,
    q10Description: text,
    q10Label: text,
    unoiName: text,
    unoiTitle: text,
    unoiDescription: text,
    unoiLabel: text,
    resourcesEyebrow: text,
    resourcesTitle: text,
    hoursLabel: text,
    suppliesLabel: text,
    activitiesLabel: text,
    documentsLabel: text,
    treasuryEyebrow: text,
    treasuryTitle: text,
    paymentsTitle: text,
    paymentsDescription: text,
    treasuryLabel: text,
    booksTitle: text,
    booksDescription: text,
    booksLabel: text,
    alumniEyebrow: text,
    alumniTitle: text,
    alumniDescription: text,
    alumniLabel: text,
  }).optional(),
  technology: z.object({
    linkHref: text,
    eyebrow: text,
    titleStart: text,
    titleEnd: text,
    titleEmphasis: text,
    introduction: text,
    image: mediaKey,
    photoCaptionStart: text,
    photoCaptionEnd: text,
    linkLabel: text,
    areas: z.array(z.object({
      name: text,
      description: text,
      href: text,
    })),
  }).optional(),
  contact: z.object({
    motto: text,
    name: text,
    fullName: text,
    url: text,
    email: text,
    address: text,
    city: text,
    phones: z.array(z.object({
      label: text,
      href: text,
    })),
    whatsapp: text,
    q10: text,
    unoi: text,
    preinscripcion: text,
    maps: text,
    mapEmbed: text,
    socials: z.array(z.object({
      label: text,
      href: text,
    })),
  }).optional(),
};
